# Generated by Django 4.0 on 2022-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_usuario', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos_usuario', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='F_Nacimiento')),
                ('correo_e', models.EmailField(max_length=254, unique=True, verbose_name='Correo_E')),
                ('genero_usuario', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Genero')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha_R')),
                ('foto', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
    ]
